### ISSUE TITLE
Allocating working buffer with 0 object size 

### ISSUE THREAD

**Issue by DPCode** [adamfk/c-filter-chain#28]
Calling ```fc_IAllocator_allocate``` with ```object_size = 0``` causes an issue where ```fc_MALLOC_FUNC``` does not return.
```
static void* fc_Mallocator_allocate(fc_IAllocator const * const allocator, size_t object_size)
{
  (void)allocator;
  void* address = fc_MALLOC_FUNC(object_size); // ! DOES NOT RETURN
  return address;
}
```

**Comment by adamfk** [comment]
In your particular case, it is the FreeRTOS pvPortMalloc function that isn't returning, but the code surrounding the working buffer should be able to handle this up front.

It was on my TODO list of things to improve and I'll get to it now :)

![image](https://user-images.githubusercontent.com/274012/40240742-e5dade16-5a7e-11e8-89ab-9771c1644f9d.png)
